### ISSUE TITLE
Dockerless CLI - User/Host Command

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-api-python3#136]
DOD
User (2 commands)
- [x] Integration tests have been added
- [ ] Implementation has been done
- [ ] Log errors/messages have received approval from Inbal + TW
Host (1 command)
- [x] Integration tests have been added
- [ ] Implementation has been done
- [ ] Log errors/messages have received approval from Inbal + TW

Helpful resources:
user/host epic - https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/101

**Comment by Tovli** [comment]
Will be done in US https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/101
