### ISSUE TITLE
conjur-cli is failing to read .conjurrc correctly and is throwing error "Account cannot be empty"

### ISSUE THREAD

**Issue by AndrewCopeland** [cyberark/conjur-api-python3#14]
When using the conjur-cli with .conjurrc the url, account and ca_bundle variables are set to None resulting in a "Account cannot be empty" exception. The reason for this is how we update the config dictionary here.
https://github.com/cyberark/conjur-api-python3/blob/master/conjur/client.py#L72-L74

To fix this issue we must filter the config of all values that are None:

```python
filtered_config = {k:v for k, v in config.items() if v is not None}
on_disk_config.update(filtered_config)
config = on_disk_config
```

**Comment by sgnn7** [comment]
@AndrewCopeland This is now fixed on master and should be released in the next version of the APIs (v0.0.3).
