### ISSUE TITLE
Document uninstall CLI

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#170]
Write down as a sub page of CLI doc and describe how the user is expected to uninstall the Conjur CLI.

DOD
- [x] Write uninstall instructions for each platform
- [x] Test them :) (BTW if you record them it will help also)
- [x] PO review
- [x] Open a doc ticket for TW

**Comment by sigalsax** [comment]
See https://ca-il-confluence.il.cyber-ark.com/display/rndp/Dockerless+CLI+-+Setup#/ under Uninstall

**Comment by InbalZilberman** [comment]
reviewed - thanks!
