### ISSUE TITLE
Packed CLI on RHEL/Windows are signed

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-api-python3#179]
On macOS/Windows machines, Anti-Viruses are flagging the packed CLI executable as a virus. A way to overcome this is by signing our executables. 

DOD
- [x] Choose to either sign exec manually or add it as part of our pipeline
- [x] Validate that this fixes the problem by running signed exec on a clean Windows machine
- [x] Sign Windows + RHEL 7/8 executables
- [x] Verify they don't alert antiviruses

**Comment by Tovli** [comment]
@sigalsax - shouldn't we separate this task to handle MacOs ?

**Comment by sigalsax** [comment]
@Tovli you are right ill close this since I was successful in signing the execs and [here](https://github.com/cyberark/conjur-api-python3/issues/225) is the new card for macos
