### ISSUE TITLE
conjur api is not authenticating in Python

### ISSUE THREAD

**Issue by cbarga** [cyberark/conjur-api-python3#21]
I am getting results back from the conjur-cli, but getting an authentication error when trying to do the same thing in Python.

[root@lncd906 ~]# conjur-cli list | head  -4  | sed '/REDACTED/s//REDACTED/'
[
    "REDACTED:policy:root",
    "REDACTED:policy:conjur/cluster/conjur",
    "REDACTED:layer:conjur/cluster/conjur",
[root@lncd906 ~]# python3
Python 3.6.8 (default, Jun 11 2019, 15:15:01)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from conjur import Client
>>> c = Client()
>>> c.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/conjur/client.py", line 115, in list
    return self._api.list_resources()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 147, in list_resources
    api_token=self.api_token,
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 90, in api_token
    self._api_token = self.authenticate()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 133, in authenticate
    self.api_key, ssl_verify=self._ssl_verify).text
  File "/usr/local/lib/python3.6/site-packages/conjur/http.py", line 62, in invoke_endpoint
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://conjurmaster-qa.REDACTED.com/authn/default/admin/authenticate
>>>

**Comment by sgnn7** [comment]
Hi @cbarga,
This is for sure an authentication issue - can you give me the list of fields (no need for their values) contained within `~/.netrc` and `~/.conjurrc`? You can try running the client with `debug flag set to maybe see what's being sent.

**Comment by cbarga** [comment]
-bash-4.2$ cat .netrc .conjurrc
machine https://conjurmaster-qa.REDACTED.com/authn
  login host/jenkins/jenkins-host
  password <REDACTED>
---
account: REDACTED
plugins: []
appliance_url: https://conjurmaster-qa.REDACTED.com
cert_file: "/var/lib/jenkins/conjur-REDACTED.pem"

**Comment by sgnn7** [comment]
@cbarga Hmm all of that seems reasonable - I do wonder if maybe the slashes in the `login` are not being escaped properly in the python code. Are you able to create a login with no slashes to test that theory out on your env? If not, I can try to set something up locally to see what kind of behavior it's expecting.

**Comment by cbarga** [comment]
I did try and login as my personal account (i.e. no slashes) and getting the same thing.

>>> c = Client(url='https://conjurmaster-qa.REDACTED.com',
...            account='REDACTED',
...            login_id='clb10',
...            password='REDACTED',
...            ca_bundle='/var/lib/jenkins/conjur-REDACTED.pem')
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/usr/local/lib/python3.6/site-packages/conjur/client.py", line 94, in __init__
    self._api.login(login_id, password)
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 110, in login
    ssl_verify=self._ssl_verify).text
  File "/usr/local/lib/python3.6/site-packages/conjur/http.py", line 62, in invoke_endpoint
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://conjurmaster-qa.REDACTED.com/authn/REDACTED/login

**Comment by cbarga** [comment]
I also used the conjur cli to login as myself (which updated .netrc) and then tried authenticating from python.

-bash-4.2$ cat .netrc
machine https://conjurmaster-qa.REDACTED.com/authn
  login clb10
  password REDACTED
-bash-4.2$ python3
Python 3.6.8 (default, Jun 11 2019, 15:15:01)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from conjur import Client
>>> c = Client()
>>> c.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/conjur/client.py", line 115, in list
    return self._api.list_resources()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 147, in list_resources
    api_token=self.api_token,
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 90, in api_token
    self._api_token = self.authenticate()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 133, in authenticate
    self.api_key, ssl_verify=self._ssl_verify).text
  File "/usr/local/lib/python3.6/site-packages/conjur/http.py", line 62, in invoke_endpoint
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://conjurmaster-qa.REDACTED.com/authn/default/clb10/authenticate
>>>

**Comment by sgnn7** [comment]
So this might be a long shot, but can you try this (appending `api` to the url):
```
Client(url='https://conjurmaster-qa.REDACTED.com/api',
    account='REDACTED',
    login_id='clb10',
    password='REDACTED',
    ca_bundle='/var/lib/jenkins/conjur-REDACTED.pem').list()
```

If that doesn't work, I might have to see if I can recreate something similar on my end.

**Comment by sgnn7** [comment]
In the meantime, what version of Conjur are you using and which version of the Python APIs?

**Comment by sgnn7** [comment]
Might be also good to know the charsets of the password since I keep thinking it's something with encoding or escaping.

**Comment by cbarga** [comment]
We are running DAP v10.11 and installed the API today, so the most recent version.  Adding api to the url did the trick.

>>> c = Client(url='https://conjurmaster-qa.REDACTED.com/api',
...   account='REDACTED',
...   login_id='clb10',
...   password='REDACTED',
...   ca_bundle='/var/lib/jenkins/conjur-REDACTED.pem'
... )
>>> c.list()[0]
'REDACTED:policy:conjur/cluster/conjur'
>>>

**Comment by sgnn7** [comment]
@cbarga yeah that makes sense - newest Conjur (depending on how it is run) may require the `/api` prefix or require no prefix depending on how it's run. Because of this, when it was written, it was decided that this prefix would be explicitly required for the Python APIs.

Given the notes above, can this issue something that can be closed?

**Comment by cbarga** [comment]
The password for the host identity has no special characters, while my personal password does have an exclamation point.

**Comment by cbarga** [comment]
Out of curiosity, I changed the url in .conjurrc and then re-authenticated from the command-line.  It works with the conjur cli, but still not working in python.

-bash-4.2$ cat .conjurrc
---
account: REDACTED
plugins: []
appliance_url: 'https://conjurmaster-qa.REDACTED.com/api'
cert_file: "/var/lib/jenkins/conjur-REDACTED.pem"
-bash-4.2$ cat .netrc
machine https://conjurmaster-qa.REDACTED.com/api
  login host/jenkins/jenkins-host
  password REDACTED
machine https://conjurmaster-qa.REDACTED.com/authn
  login host/jenkins/jenkins-host
  password REDACTED
machine https://conjurmaster-qa.REDACTED.com/api/authn
  login host/jenkins/jenkins-host
  password REDACTED

**Comment by cbarga** [comment]
>>> from conjur import Client
>>> c = Client()
>>> c.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/conjur/client.py", line 115, in list
    return self._api.list_resources()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 147, in list_resources
    api_token=self.api_token,
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 90, in api_token
    self._api_token = self.authenticate()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 133, in authenticate
    self.api_key, ssl_verify=self._ssl_verify).text
  File "/usr/local/lib/python3.6/site-packages/conjur/http.py", line 62, in invoke_endpoint
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://conjurmaster-qa.REDACTED.com/api/authn/default/host%2Fjenkins%2Fjenkins-host/authenticate
>>>

**Comment by sgnn7** [comment]
Hmm... can you try leaving only this in the netrc and trying python api? This might be a different thing.

```
machine https://conjurmaster-qa.REDACTED.com/api/authn
login host/jenkins/jenkins-host
password REDACTED
```

**Comment by cbarga** [comment]
That resulted in the same error but did not break the conjur cli (as I half-expected).

**Comment by sgnn7** [comment]
So I think I have enough info to take a deeper look into this today or tomorrow as what you have _should_ in theory work. I don't know why your last changes don't work. Just to be 100% sure I am working with proper assumptions, your username can log in fine w/ conjurrc/netrc but the host can't?

**Comment by cbarga** [comment]
No.  When I first authenticate with the conjur cli, using my personal username, and then use python, I get the same error.

-bash-4.2$ conjur authn login -u clb10
Please enter clb10's password (it will not be echoed):
Logged in
-bash-4.2$ python3
Python 3.6.8 (default, Jun 11 2019, 15:15:01)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from conjur import Client
>>> c = Client()
>>> c.list()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/conjur/client.py", line 115, in list
    return self._api.list_resources()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 147, in list_resources
    api_token=self.api_token,
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 90, in api_token
    self._api_token = self.authenticate()
  File "/usr/local/lib/python3.6/site-packages/conjur/api.py", line 133, in authenticate
    self.api_key, ssl_verify=self._ssl_verify).text
  File "/usr/local/lib/python3.6/site-packages/conjur/http.py", line 62, in invoke_endpoint
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://conjurmaster-qa.REDACTED.com/api/authn/default/clb10/authenticate
>>>

**Comment by cbarga** [comment]
Out of curiosity, I tried using the conjur-cli tool in python as a subprocess and it works:

>>> secret = 'QA-CyberArkVault/Jenkins/DAP_Automation/dap_automation-arp_api/password'
>>> p = subprocess.Popen(["/usr/local/bin/conjur-cli", "variable", "get", f'{secret}'], stdout=subprocess.PIPE)
>>> p.communicate()[0]
b'45ff0a48-c39f-4559-a63d-87c510a4074e'
>>>

**Comment by sgnn7** [comment]
@cbarga Ah ok - so specifying config in the `Client()` worked [here](https://github.com/cyberark/conjur-api-python3/issues/21#issuecomment-555685987) but the rest didn't. That should be enough for me to start working on this issue locally.

**Comment by sgnn7** [comment]
@cbarga I'm having trouble recreating this error locally. My test setup is below but I want to point out that *`.netrc` password is in actuality an API key and **not** the login password* so I wonder if that's the problem.

# DAP:
```
$ docker run -d --security-opt seccomp:unconfined --name conjur-appliance2 -p 443:443 <REDACTED>/conjur-appliance:10.10
$ docker exec conjur-appliance2 evoke configure master -h localhost -p mypassword default 
...
Configuration successful. Conjur master up and running.
```

# Python Client

`./.conjurrc`
```
---
account: default
plugins: []
appliance_url: 'https://localhost/api'
cert_file: "<redacted_abs_path>/cert.pem"
```

`./.netrc`
``` 
machine https://localhost/api/authn
  login admin
  password 3d9c6yv3xgz4ft218dd0z5rknv3fnnxe42fdy91y3pt4cj646ht3g
```

Running
```
$ # Get an isolated env
$ python3 -m venv venv
$ source venv/bin/activate

$ # Install Pypi package
$ echo conjur-client > requirements.txt
$ pip3 install -r requirements.txt 

$ # Grab SSL cert
$ openssl s_client -showcerts \
  -connect localhost:443 </dev/null 2>/dev/null | sed -n -e '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p' > cert.pem

$ HOME=$(pwd) python3 -c 'from conjur import Client;Client().list()'
 <Nothing printed since I don't have any policies loaded but no auth errors>
 
$ echo $?
 0
```

# `conjur-cli` Client

```
$ docker pull cyberark/conjur-cli:5
$ mkdir foo

$  docker run --rm --net=host -it -v $(pwd)/foo:/root cyberark/conjur-cli:5

root@docker-desktop:/# conjur init -u https://localhost/api
SHA1 Fingerprint=C7:54:85:D0:16:2E:37:FA:5B:3B:43:2D:64:56:30:B7:88:54:78:34
Please verify this certificate on the appliance using command:
              openssl x509 -fingerprint -noout -in ~conjur/etc/ssl/conjur.pem
Trust this certificate (yes/no): yes

Enter your organization account name: default

Wrote certificate to /root/conjur-default.pem
Wrote configuration to /root/.conjurrc

root@docker-desktop:/# conjur authn login
Enter your username to log into Conjur: admin
Please enter your password (it will not be echoed): 
Logged in 

root@docker-desktop:/# cat ~/.conjurrc 
---
account: default
plugins: []
appliance_url: https://localhost/api
cert_file: "/root/conjur-default.pem" 

root@docker-desktop:/# cat ~/.netrc    
machine https://localhost/api/authn
  login admin
  password 3d9c6yv3xgz4ft218dd0z5rknv3fnnxe42fdy91y3pt4cj646ht3g

root@docker-desktop:/# conjur list                                                                                                                                                                                                                                  
[                                                  
                                                                                                                                  
] 
```
^ you can see that these files are practically identical to ones from my manually entered ones

I then tried to use the conjur-cli generated files as input into python (I had to fix the cert path) and it worked fine too. At this point, I can't quite tell what might be causing the issue since afaict it's all behaving as expected.

@cbarga Any thoughts on maybe how my env might be different from yours?

**Comment by sgnn7** [comment]
@cbarga Just following up: Any updates/insights given my testing data above?

**Comment by cbarga** [comment]
Sorry I missed your earlier comment.  I don't have any insights, unfortunately.  I did decide to just use summon, since I just need to look up a couple of variables.  So, maybe we can just mark this down as something odd with our environment.

**Comment by cbarga** [comment]
I think I will spin up a development environment that I can test further, because I would like to play around with your module.

**Comment by sgnn7** [comment]
@cbarga No problem and testing would be greatly appreciated! :)

I will close this for now but if you find out that it's not environment-related, please reopen this issue as other users may have it as well.

PS: If you're looking up a few variables, don't forget that this module can pull them in batches too: https://github.com/cyberark/conjur-api-python3#get_manyvariable_idvariable_id

**Comment by cbarga** [comment]
I tested and it looks like your code expects the account name to be 'default'.  When I started and 'evoke configure'd the container with 'default' as the account, it works fine.  When I 'evoke configure' as a different account, it gets the error.  Now that I look back at my very first comment, I see 'default' in the url.

https://conjurmaster-qa.redacted.com/authn/default/admin/authenticate
                                                                                 ^^^^^^^

**Comment by cbarga** [comment]
...well, the arrows didn't line up, but it's after 'authn'

**Comment by sgnn7** [comment]
@cbarga Hmm.. that could be it (I didn't realize that `REDACTED` in conjurrc in your second post was not the same as `default`). Let me retry my experiment with a non-`default` account and see if I can recreate it.

**Comment by sgnn7** [comment]
@cbarga Good news - I identified and fixed the bug! 

Release is [`v0.0.4`](https://github.com/cyberark/conjur-api-python3/releases/tag/v0.0.4) and you can get the fix with `pip install --upgrade conjur-client`. I'll close this issue and let us know if it doesn't work for you.

**Comment by cbarga** [comment]
Sweet!  Thank you!  I have upgraded and confirmed that Client.list() works as expected.
    On Thursday, November 21, 2019, 05:42:54 PM EST, Srdjan Grubor <notifications@github.com> wrote:  
 
 
@cbarga Good news - I identified and fixed the bug!

Release is v0.0.4 and you can get the fix with pip install --upgrade conjur-client. I'll close this issue and let us know if it doesn't work for you.
