### ISSUE TITLE
Correction to variable CLI command help

### ISSUE THREAD

**Issue by pdavid2** [cyberark/conjur-api-python3#227]
You have (for both the command and the subcommand):
`conjur variable get -i secrets/mysecret,“secrets/my secret” Get the values of the variables secrets/mysecret1 and “secrets/my secret”`

mysecret1 should be mysecret

You have curly quotation marks around secrets/my secret. Is that OK or should they be straight quotation marks?

**Comment by eranha** [comment]
Already fixed
