### ISSUE TITLE
Correction to user CLI command help

### ISSUE THREAD

**Issue by pdavid2** [cyberark/conjur-api-python3#229]
In the user command help output:
For both subcommands, you have Usage as : `conjur [global options] user <**subcommand**> [options] [args]`
That should be:

- `conjur [global options] user rotate-api-key [options][args]`
- `conjur [global options] user change—password [options][args]`

For rotate-api-key, you say:

- In the definition of the -i option: "Default: logged-in user"
- In an Example (no -i option): "Prompts for the user for whom you want to rotate the API key"

These statements are contradictory - the example should say "Rotates the API key of the logged-in user"

**Comment by eranha** [comment]
Already fixed

**Comment by eranha** [comment]
Already fixed
