### ISSUE TITLE
Correction to host CLI command help

### ISSUE THREAD

**Issue by pdavid2** [cyberark/conjur-api-python3#230]
In the host command help output:
For the subcommand, you have Usage as : `conjur [global options] host <subcommand> [options][args]`
That should be:
`conjur [global options] host rotate-api-key [options][args]`

**Comment by sigalsax** [comment]
@pdavid2 the general command should be <subcommand>. host has two subcommands 1. rotate-api-key and 2. change-password. The main host page should have <subcommand>

**Comment by sigalsax** [comment]
would be helpful if you opened a PR pointing to the exact text you are referencing

@pdavid2 @eranha

**Comment by eranha** [comment]
Already fixed
