### ISSUE TITLE
CLI - Research headless Windows server keyring

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-api-python3#237]
We are not sure if a headless Windows server (without GUI) comes with keyring. If not, we need to understand the steps required to install the keyring and what types of test need to be run

DOD
- [ ] Research if keyring comes out of box on headless windows server
- [ ] Inform Inbal and come to a decision if we want to support this
- [ ] If does not come out of box, talk to @eladkug to figure out what types of tests we want to run

**Comment by moticless** [comment]
**It was decided not to support CLI for headless windows (Windows Server Core).**

What tested so far:
- Created Windows Server Core image on AWS:  Windows_Server-2016-English-Core-Base-2021.03.10
- Created SFTP server to copy files into windows machine
- Powershell install on Windows Server Core 'Posh-SSH' for ftp.
- All my attempts to download files with powershell from ftp server got failed (FTP from mac/linux succeeded)
