### ISSUE TITLE
Evaluate EE of Refactoring  the CLI main class

### ISSUE THREAD

**Issue by eranha** [cyberark/conjur-api-python3#251]
Trying to estimate how much work/time it will take to refactor cli.py

DoD

- [x] Skeleton of the refactor
- [x] EE of refactoring

**Comment by eranha** [comment]
Refactoring in Python CLI
	• Extract main menu (1)
	• Actions (5)
		○ Wrap actions (e.g. init/login/load_policy) in  action class
		○ An action has input, output, message, is_error
		○ Review the attached illustration of the the resource/actions tree
		○ Actions will get pre-mapped to their respective resource/action in the menu and will get executed by the without the need of a long if/else statements , the output will get delegated to the view.
	• View (3)
		○ View is an abstraction of how we display output to the user
		○ Controller and actions remain indifference to how the output gets displayed
		○ It enables a more fine grain control over the output in a single component
			§ Use case automation needs only the output without any user interaction decoration
	• State (un_initialized / initialized / logged_in) (3)
		○ Upon CLI startup it will evaluate its state and enable the action  that can execute in the applicable state.
		○ E.g. actions under the tree path init/login can execute in logged_in state
	• Mode (testing/production) (1)
	• Extract all messages out of the code to a separate file (4)
		○ Each message will have its own id
		○ The code will reference the messages using their ids.
		○ E.g. set_variable action will return message id: 103 upon a successful completion of the execution
It will make  the code cleaner easy to maintain and i18n ready![tree.png](https://images.zenhubusercontent.com/5e7352b31e94435c07d16166/de7c09b2-7cbe-420c-8fe9-3f6f7b4bf176)

**Comment by sigalsax** [comment]
Looks great and makes more sense in my 🧠 ! 

#### Actions: 

I am missing a more low level design though and how things will connect. Would be really helpful to have a flow diagram here.

#### State:
How will the state be evaluated? will we have a config file?

#### Mode:
How will mode be determined? Will it be saved the same as state?

#### Extract all messages out of the code to a separate file
Don't understand the the example but do you mean all messages INFO/DEBUG/WARNING have their own codes?

**Comment by eranha** [comment]
@sigalsax 
>Does this mean the Controller won't be printing to STDOUT?
No.
There will be a single controller, commands , and a view
```
class View(object):

    @staticmethod
    def show_item(item_type, item, item_info):
        print('//////////////////////////////////////////////////////////////')
        print('Good news, we have some {}!'.format(item.upper()))
        print('{} INFO: {}'.format(item_type.upper(), item_info))
        print('//////////////////////////////////////////////////////////////')

class Controller(object):    
    commands = {
     "init": new InitCommand(),
     "login": new LoginCommand(),
     "whoami": new WhoAmICommand() 
   }
    def __init__(self, model, view):
        self.model = model
        self.view = view

    def execute_cmd(self, cmd, args):
        if commands[cmd].can_execute_on_state(current_state):
            output, message = commands[cmd].execute(args)
            self.view.show_command_output(output, message)
       else
           handle_cmd_not_allowed_on_state(commands[cmd])

class BaseCommand(object):
  def execute_on_state():
     return State.LOGGED_IN

class Login(BaseCommand):
    def execute_on_state():
       return State.INITIALIZED

class WhoAmICommand(BaseCommand):
   def name():
     return "whoami"
   
   def execute():
     return client.whoami()
```

> How will mode be determined? Will it be saved the same as state?
State gets evaluated on startup?.
Mode (TEST/CI/PROD)? will be evaluated based on an env param as today but I suggest to create separate flow for each mode.
Use case: in CI mode , view will only print the output and not user facing messeages

>Don't understand the the example but do you mean all messages INFO/DEBUG/WARNING have their own codes?
I was referring to user facing messages not log messages.

**Comment by sigalsax** [comment]
A couple of questions come to mind:
- Each controller has its own logic.py file that holds the BL for each controller currently?
-  ```
```
def execute_on_state():
     return State.LOGGED_IN
```
what does State look like? How is it set? For example, how is LOGGED_IN checked for each value?

IMO MODE should be part of a config file that holds the State. WDYT?

**Comment by sigalsax** [comment]
At a high level:
- 1 controller with commands (init, login, user...) and all command has actions (rorate-api-key, change password, etc). Each command has a function can_execute that decides if the action can be run


State:
State is decided if the files exist with proper content
- Initialized/uninitialized
- Login

View:
- Responsibility - takes the result and in charge of printing to the user

**Comment by eranha** [comment]
Creates issues in R&D Boost

**Comment by sigalsax** [comment]
@eranha please add the link to the issues you created before closing so that way it will be easier to track 🙏
