### ISSUE TITLE
Conjur init returns -1 unexpected EOF 

### ISSUE THREAD

**Issue by uCatu** [cyberark/conjur-api-python3#290]
## Summary
When running conjur init on self-signed/expired certificate, we receive non-informative error
![image](https://user-images.githubusercontent.com/50704381/116208338-802fce80-a749-11eb-8259-d43eb57872d9.png)

## Steps to Reproduce
See image above

## Expected Results
If we don't support self-signed we should return a meaningful error. 
or at least specify the resolution - `--insecure`

## Actual Results (including error logs, if applicable)
See image above

## Reproducible
   * [x ] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible

**Comment by sigalsax** [comment]
@uCatu can you please provide more detailed information of what your architecture looks like, where the certificate lives (in LB or on the server), information about your server (TLS version, etc), and maybe even the certificate so we can better understand why you are getting this.

**Comment by sigalsax** [comment]
Important note, Ruby CLI returns a similar error: 
```
Please enter your password (it will not be echoed):
error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
```

**Comment by eladkug** [comment]
Duplicate to https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-10129
