### ISSUE TITLE
Create/build new release

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-api-python3#54]
Currently we have a number of changes that are on master that would be useful to end users. This issue is to track this new release (probably v0.1.0).

AC:
- [x] A new release of this project is done
- [x] Smoke test of the binaries produced is done

**Comment by subodh-shrivastava** [comment]
@sgnn7 we have an interest in this API, however as an enterprise user we are reluctant to use a library marked as alpha, are there any plans to make this production environment grade?
If yes do you know when will this be made available for production environment use?

**Comment by sgnn7** [comment]
Hey @subodh-shrivastava!
Great question and yes we have plans for it but I would like to leave the answer to this particular question to @izgeri since she overlooks the OSS project priority queue. Majority of the things left to get this API to the production grade I believe are mostly paperwork (contributing docs, issue templates, etc) but there may be some things that I'm missing so I can't speak with certainty.

**Comment by sgnn7** [comment]
Closed via #72 

@subodh-shrivastava: Certification level for this repo might be increasing soon so keep an eye on the project in the following weeks.
