### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by jeroenvanroon** [cyberark/conjur-api-python3#75]
There is a typo in the latest setup.py commit. Version "PyYAML>=5.31" needs to be "PyYAML>=5.3.1".

**Comment by sgnn7** [comment]
Hey @jeroenvanroon, thank you for reporting this issue!

It's strange that the CI/CD pipeline didn't catch this issue but I've [opened a pull request to fix it](#76) and I'll open an issue to add a test for validation of these values.

Thanks again for the bug report!

Srdjan

**Comment by sgnn7** [comment]
Hey @jeroenvanroon, the fix is merged now!

**Comment by jeroenvanroon** [comment]
Hello @sgnn7, thank you for fixing! My playbooks work on the latest push now.
