### ISSUE TITLE
Python CLI as a GA

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#82]
Overview

Priority 
[deployment CLI](https://app.zenhub.com/workspace/o/cyberark/conjur-api-python3/issues/78)
[init Command](https://app.zenhub.com/workspace/o/cyberark/conjur-api-python3/issues/79)
[login logout commands](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/119)
[variable commands](https://app.zenhub.com/workspace/o/cyberark/conjur-api-python3/issues/80)
[list Command](https://app.zenhub.com/workspace/o/cyberark/conjur-api-python3/issues/81)
[policy actions](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/112)
[host and user actions](https://app.zenhub.com/workspace/o/cyberark/conjur-api-python3/issues/101)
[CLI UX](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/132)
[CLI UT](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/133)
[CLI Docs](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/131)
[Release ready CLI](https://app.zenhub.com/workspaces/appliance-development-5c9cf04bfa1c204b63eddcc6/issues/cyberark/conjur-api-python3/110)
CLI - Release automation design

**Comment by daphnaab** [comment]
https://eu1.clarizen.com/Clarizen/Task/6691240709?orgId=28516677

**Comment by sigalsax** [comment]
closing as we are GA (:
